title: Reuben Varghese Jose
avatar : "/assets/images/reubenprofile.jpg" 
email: reuben.varghesejose@gmail.com
description: >-
  Engineer turned consultant passionate about sustainable impact, storytelling, and career transformation.
baseurl: "" 
url: "https://ReubenVJose.github.io"
remote_theme: "mmistakes/minimal-mistakes"
#minimal_mistakes_skin: "default"
search: true

author:
  name   : "Reuben Varghese Jose"
  bio    : "Engineer turned consultant passionate about sustainable impact, storytelling, and career transformation."
  location: "Mumbai, India"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:reuben.varghesejose@gmail.com"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/reuben-varghese-jose-03a7641a2/"
    - label: "Instagram"
      icon: "fab fa-instagram"
      url: "https://www.instagram.com/reubenjose/"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      author_profile: true
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
      author_profile: true

paginate: 5
paginate_path: /page:num/
timezone: Asia/Kolkata

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-archives
  - jekyll-include-cache

collections:
  pages:
    output: true
    permalink: /:title/
